# Determines if we search the title (optional). Defaults to true.
matchTitle: false

# Determines if we search the body (optional). Defaults to true.
matchBody: true

# Determines if label matching is case sensitive (optional). Defaults to true.
caseSensitive: true

# Explicit keyword mappings to labels. Form of match:label. Required.
labelMappings:
  Collection: collection
  Video: video
  Blog: blog
  Tutorial: tutorial
  Exploratory: exploratory
  Level-Up: level-up
  Livestream: livestream
  How-To: how-to
  Talk: talk
  Workshop: workshop
  Supernovas: supernovas
  Events: events
  Non-profits: non-profits
  Reporting: reporting
  Operations: operations
  Sourcing: sourcing
  Other Programs: other-programs
  Release notes: release-notes
