name: Content Request
description: Request creation of new content that you want to see available on Postman platforms. 
title: "Content Title Goes Here"
body:
- type: textarea
  attributes:
    label: Describe the content you'd like to see
    description: |
      A clear and concise description of the content needed, the persona.
  validations:
    required: true
- type: dropdown
  id: type
  attributes:
    label: Content Type
    multiple: true
    options:
      - Collection
      - Video
      - Blog
      - Tutorial
- type: dropdown
  id: video-type
  attributes:
    label: If the request is for a video, indicate which type?
    multiple: false
    options:
      - How-To
      - Exploratory
      - Level-Up
      - Other
  validations:
    required: false
