name: Content Request
description: Request creation of new content that you want to see available on Postman platforms. 
title: "Content Title Goes Here"
labels: "content"
body:
- type: textarea
  attributes:
    label: Describe the content you'd like to see
    description: |
      A clear and concise description of the content needed, the persona.
  validations:
    required: true
- type: dropdown
  id: type
  attributes:
    label: Content Type
    multiple: true
    options:
      - Collection
      - Video
      - Blog
      - Tutorial
  validations:
    required: true
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://www.postman.com/legal/community-code-of-conduct/)
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
