name: Program Request
description: Request a creation, general change or activity on the programs part of DevRel. 
title: "Program Request Goes Here"
body:
- type: textarea
  attributes:
    label: Describe the creation, change or activity you'd like to see
    description: |
      A clear and concise description of the work needed to make this happen.
  validations:
    required: true
- type: dropdown
  id: type
  attributes:
    label: Program
    multiple: false
    options:
      - Supernova
      - Event Sponsorship
      - Event Prioritization
      - Postman-Blog
      - Non-Profit
      - Reporting (Trip Reports, CfPs, Speaking)
      - Other
  validations:
    required: true
- type: dropdown
  id: category
  attributes:
    label: Please categorize your Isue by selecting one or more of these types.
    multiple: true
    options:
      - Interaction
      - Website 
      - Promotion
      - Pipeline
      - Operations
      - Sourcing
      - Call for Proposals
      - Trip Reports
      - Orbit
      - Looker
  validations:
    required: false
