name: Program Request
description: Request a creation, general change or activity on the programs part of DevRel. 
title: "Program Request Goes Here"
labels: programs
body:
- type: textarea
  attributes:
    label: Describe the creation, change or activity you'd like to see
    description: |
      A clear and concise description of the work needed to make this happen.
  validations:
    required: true
- type: dropdown
  id: type
  attributes:
    label: Program
    multiple: false
    options:
      - Supernovas
      - Events
      - Non-profits
      - Other Programs
  validations:
    required: true
- type: dropdown
  id: category
  attributes:
    label: Please categorize your Issue by selecting one or more of these types.
    multiple: true
    options:
      - Operations
      - Sourcing
      - Reporting
  validations:
    required: false
