name: Auto Assign Issues to Projects

on:
  issues:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    name: Assign issue to project
    steps:
    - name: Assign new issues to Content Project
      if: contains(github.event.issue.labels.*.name, 'content')
      uses: srggrs/assign-one-project-github-action@1.2.0
      with:
        project: 'https://github.com/orgs/postmanlabs/projects/11'
        column_name: 'Backlog'
    - name: Assign new issues to Programs Project
      if: contains(github.event.issue.labels.*.name, 'programs')
      uses: srggrs/assign-one-project-github-action@1.2.0
      with:
        project: 'https://github.com/orgs/postmanlabs/projects/11'
        column_name: 'Backlog'
